logging:
    level:
        ROOT: DEBUG
        com.ecommerce.bookstore: DEBUG
server:
    port: 8082

spring:
    profiles:
        active: test

    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: false
        database-platform: org.hibernate.dialect.H2Dialect

    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: root
        password: admin 

    h2:
        console:
            enabled: true
            path: /h2
app:
    jwt:
        token: 
            secret: 21bVPgn9p1pSfjUi5B57vuleRikZ0I3Q58ThEyhO6GAG3qTj4cJyNKuk/GFlpmu0QalAC1SVlOme2jHbHQ1x3w==
            # 24 hours
            expiration: 24
# Command line: mvn spring-boot:run -Dspring-boot.run.profiles=test
# shout out to: https://github.com/pavankjadda/BookStore