# logging:
#     level:
#         ROOT: DEBUG
#         com.ecommerce.bookstore: DEBUG
server:
    port: 8082
    error:
        include-stacktrace: never # Keep dev tools and turn off stack trace on Server Response.
spring:
    profiles:
        active: test
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: false
        database-platform: org.hibernate.dialect.H2Dialect
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:testdb
        username: root
        password: admin 
    h2:
        console:
            enabled: true
            path: /h2
    mail:
        host: smtp.mailtrap.io
        port: 2525
        username: a29d3bf8f10124
        password: 76422c95d8a2bc
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
app:
    jwt:
        token: 
            secret: 21bVPgn9p1pSfjUi5B57vuleRikZ0I3Q58ThEyhO6GAG3qTj4cJyNKuk/GFlpmu0QalAC1SVlOme2jHbHQ1x3w==
            expiration: 24 # 24 hours
    mail:
        from: bookstore@localhost
        base-url: http://127.0.0.1:8082
    cors:
        allowed-origins:
            - http://localhost:4000
            - http://localhost:3000

# Notes:
# Command line: mvn spring-boot:run -Dspring-boot.run.profiles=test
# Source to help create test, dev, & prod profile yaml files: https://github.com/pavankjadda/BookStore